config/routes.rb
IssueTracker::Application.routes.draw do
  root "welcome#show"
  devise_for :users
  resources :users
  resources :projects do
    resources :issues do
      member do
        put 'assign_user', to: 'issues#assign_user', as: 'assign_user'
      end
      resources :comments do
        resources :likes, only: [:create]
      end
    end
    resources :memberships
    get 'members', to: 'users#index', as: 'users'
    resources :topics do
      resources :posts
    end
  end
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body, type: String
  
  belongs_to :user
  belongs_to :issue
  has_many :likes

  validates :user_id, presence: true
  validates :issue_id, presence: true
  validates :body, presence: true


  def liked? user
    likes.mine(user).present?
  end

  def can_like? user
    true unless self.liked?(user) || self.user == user
  end

end

app/models/issue.rb
class Issue
  include Mongoid::Document
  field :subject, type: String
  field :description, type: String
  field :priority, type: String
  field :type, type: String
  field :state, type: String, default: 'open'


  belongs_to :project
  belongs_to :assignee, class_name: 'User'
  belongs_to :creator, class_name: 'User', inverse_of: :issues
  has_many :comments
  

  TYPES = %w(bug enhancement)
  PRIORITIES = %w(minor normal major critical)
  STATES = %w(open fixed)

  validates :subject, presence: true
  validates :type, inclusion: { in: TYPES }
  validates :priority, inclusion: { in: PRIORITIES }
  validates :state, inclusion: { in: STATES }

  scope :open, -> { where(state: 'open') }
  scope :fixed, -> { where(state: 'fixed') }
  scope :mine, ->(user) { where(assignee: user) }
  
end

app/models/like.rb
class Like

  include Mongoid::Document
  
  belongs_to :user
  belongs_to :comment

  scope :mine, ->(user) { where(user_id: user) }
end

app/models/membership.rb
class Membership
  include Mongoid::Document

  belongs_to :user
  belongs_to :project

  validates :user_id, presence: true
  validates :project_id, presence: true
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body, type: String

  belongs_to :topic
  belongs_to :user

  validates :body, length: { minimum: 5, maximum: 10000 }
end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :description, type: String
  field :homepage, type: String

  belongs_to :user
  has_many :issues
  has_many :memberships
  has_many :topics

  validates :title, presence: true

  def member? user
    Membership.where(user_id: user.id, project_id: self.id).present?
  end

  def members
    User.in(id: memberships.map(&:user_id))
  end

  def users_available_to_invite
    User.not_in(id: memberships.map(&:user_id))
  end

end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String

  belongs_to :user
  belongs_to :project
  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts

  validates :title, length: { minimum: 5, maximum: 50 }
  validates :user_id, presence: true
  validates :project_id, presence: true

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time
  field :remember_created_at, type: Time
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  field :first_name, type: String
  field :last_name, type: String
  field :position, type: String

  has_many :projects
  has_many :memberships
  has_many :issues, inverse_of: :creator
  has_many :topics
  has_many :posts
  has_many :comments

  POSITIONS = ['developer', 'project manager', 'other']

  def to_s
    full_name.strip.empty? ? email : full_name
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def projects_member
    Project.in(id: memberships.map(&:project_id))
  end

  def issues_assigned
    Issue.in(assignee: self)
  end

  def technical?
    position == 'developer' || position == 'project manager'
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :deny_access, unless: :project_member?
  expose(:project)
  expose(:issue, attributes: :issue_params)
  expose(:issues) { project.issues }


  def create
    issue.creator = current_user
    if issue.save
      redirect_to project_issue_path(project, issue)
    else
      render :new
    end
  end

  def update
    if issue.save
      redirect_to project_issue_path(project, issue)
    else
      render :edit
    end
  end

  def assign_user
    issue = Issue.find(params[:id])
    issue.update(assignee: current_user) if current_user.technical?
    redirect_to project_issue_path(project, issue)
  end

  private
    def issue_params
      params.require(:issue).permit(:subject, :description, :priority, :type, :state)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  expose(:like)
  expose(:comment)

  def create
    unless comment.liked?(current_user) || comment.user == current_user
      like = comment.likes.build(user_id: current_user.id)
      like.save 
    end
    redirect_to :back
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :deny_access, unless: :project_member?
  expose(:topic)
  expose(:post, attributes: :post_params)
  expose(:posts)

  def create
    post.topic = topic
    post.user = current_user
    if post.save
      redirect_to project_topic_path(topic.project, topic)
    else
      redirect_to :back
    end
  end

  def update
    if post.save
      project_topic_path(topic.project, topic)
    else
      render :edit
    end
  end

  private
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :deny_access, unless: :project_member?
  expose(:project)
  expose(:topic, attributes: :topic_params)
  expose(:topics)
  expose(:post) { Post.new }

  def create
    topic.user = current_user
    topic.project = project
    if topic.save
      redirect_to project_topic_path(project, topic)
    else
      render :new
    end
  end

  def update
    if topic.save
      redirect_to project_topic_path(project, topic)
    else
      render :edit
    end
  end

  private
    def topic_params
      params.require(:topic).permit(:title, posts_attributes: [:id, :body, :user_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  expose(:project)
  expose(:user)
  expose(:users)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper

  def show_assignee assignee
    assignee.present? ? assignee : 'unassigned'
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def show_homepage homepage
    if project.homepage.present?
      link_to homepage, "http://#{project.homepage}"
    else
      'unknown'
    end
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def show_time time
    time.strftime("%a %m/%d/%y")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/issues/_form.html.haml
.col-xs-6
  = simple_form_for [project, issue] do |form|
    = form.input :subject
    = form.input :description
    %p
      = form.input :priority, collection: Issue::PRIORITIES
    %p
      = form.input :type, collection: Issue::TYPES

    = form.submit class: 'btn btn-primary'

app/views/issues/_issue.html.haml
%tr
  %td= link_to issue.subject, project_issue_path(project, issue)
  %td= issue.priority
  %td= issue.type
  %td= issue.state
  %td= show_assignee(issue.assignee)

app/views/issues/new.html.haml
= render 'form'

app/views/issues/show.html.haml
.panel.panel-default
  .panel-heading
    = issue.subject
  .panel-body
    %p
      = issue.description
    %p
      %strong Priority:
      = issue.priority
    %p
      %strong Type:
      = issue.type
    %p
      = simple_form_for [project, issue] do |form|
        %strong State:
        = issue.state
        = form.select :state, ["open", "fixed"]
        = form.submit 'change', class: "btn btn-default btn-xs"
    %p
      %strong Assignee:
      = show_assignee(issue.assignee)
      = link_to 'Assign to me', assign_user_project_issue_path(issue.project, issue), class: "btn btn-default btn-xs", method: :put

%h4 Comments:
= render issue.comments
%button{type: "button", class: 'btn btn-default btn-sm', id: 'newComment'} New comment

%p
  #commentForm.hidden
    = render 'comments/form'

app/views/posts/_form.html.haml
= simple_form_for [project, topic, post] do |form|
  .row
    .col-xs-6
      = form.input :body, as: :text, input_html: { cols: 50, rows: 10 }
      = form.submit class: 'btn btn-primary'

app/views/posts/_post.html.haml
.panel.panel-default
  .panel-heading
    %span Added by: 
    = link_to post.user, user_path(post.user)
    = "#{time_ago_in_words(post.created_at)} ago"   
  .panel-body
    %p
      = post.body

app/views/topics/_form.html.haml
.col-xs-6
  = simple_form_for [project, topic] do |form|
    .row
      = form.input :title
      = form.simple_fields_for :posts, post do |post|
        = post.input :body, as: :text, input_html: { cols: 50, rows: 10 }
        = post.hidden_field :user_id, value: current_user.id
      = form.submit class: 'btn btn-primary'

app/views/topics/_topic.html.haml
%tr
  %td= link_to topic.title, project_topic_path(project, topic)
  %td= topic.posts.count

app/views/topics/new.html.haml
= render 'form'

app/views/topics/show.html.haml
%h3= topic.title

= render topic.posts

= render 'posts/form'

app/views/users/index.html.haml
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Name
      %th Email
      %th Position
      %th Projects
      %th Issues
  %tbody
    - users.each do |user|
      %tr
        %td= link_to user.full_name, user_path(user)
        %td= user.email
        %td= user.position
        %td= user.projects_member.count
        - if user.issues_assigned.count == 0
          %td{style: "color: red;"}= user.issues_assigned.count
        - else
          %td= user.issues_assigned.count

app/views/users/show.html.haml
.panel.panel-default
  .panel-heading
    = user
  .panel-body
    %p
      %strong Email:
      = mail_to user.email
    %p
      %strong Registered on:
      = show_time(user.created_at)
    %p
      %strong Last connection:
      = show_time(user.last_sign_in_at)

    %br
    %h4 Projects
    - user.projects_member.each do |project|
      %p
        = link_to project.title, project

    %br
    %h4 Activity
    = "Reported issues: #{user.issues.count}"