config/routes.rb
IssueTracker::Application.routes.draw do
  root "welcome#show"
  devise_for :users
  resources :users
  resources :projects do
    resources :issues do
      member do
        put 'assign_user', to: 'issues#assign_user', as: 'assign_user'
      end
      resources :comments do
        resources :likes, only: [:create]
      end
    end
    resources :memberships
    get 'members', to: 'users#index', as: 'users'
    resources :topics do
      resources :posts
    end
  end
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body, type: String
  
  belongs_to :user
  belongs_to :issue
  has_many :likes

  validates :user_id, presence: true
  validates :issue_id, presence: true
  validates :body, presence: true


  def liked? user
    likes.mine(user).present?
  end

  def can_like? user
    true unless self.liked?(user) || self.user == user
  end

end

app/models/issue.rb
class Issue
  include Mongoid::Document
  field :subject, type: String
  field :description, type: String
  field :priority, type: String
  field :type, type: String
  field :state, type: String, default: 'open'


  belongs_to :project
  belongs_to :assignee, class_name: 'User'
  belongs_to :creator, class_name: 'User', inverse_of: :issues
  has_many :comments
  

  TYPES = %w(bug enhancement)
  PRIORITIES = %w(minor normal major critical)
  STATES = %w(open fixed)

  validates :subject, presence: true
  validates :type, inclusion: { in: TYPES }
  validates :priority, inclusion: { in: PRIORITIES }
  validates :state, inclusion: { in: STATES }

  scope :open, -> { where(state: 'open') }
  scope :fixed, -> { where(state: 'fixed') }
  scope :mine, ->(user) { where(assignee: user) }
  
end

app/models/like.rb
class Like

  include Mongoid::Document
  
  belongs_to :user
  belongs_to :comment

  scope :mine, ->(user) { where(user_id: user) }
end

app/models/membership.rb
class Membership
  include Mongoid::Document

  belongs_to :user
  belongs_to :project

  validates :user_id, presence: true
  validates :project_id, presence: true
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body, type: String

  belongs_to :topic
  belongs_to :user

  validates :body, length: { minimum: 5, maximum: 10000 }
end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :description, type: String
  field :homepage, type: String

  belongs_to :user
  has_many :issues
  has_many :memberships
  has_many :topics

  validates :title, presence: true

  def member? user
    Membership.where(user_id: user.id, project_id: self.id).present?
  end

  def members
    User.in(id: memberships.map(&:user_id))
  end

  def users_available_to_invite
    User.not_in(id: memberships.map(&:user_id))
  end

end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String

  belongs_to :user
  belongs_to :project
  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts

  validates :title, length: { minimum: 5, maximum: 50 }
  validates :user_id, presence: true
  validates :project_id, presence: true

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time
  field :remember_created_at, type: Time
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  field :first_name, type: String
  field :last_name, type: String
  field :position, type: String

  has_many :projects
  has_many :memberships
  has_many :issues, inverse_of: :creator
  has_many :topics
  has_many :posts
  has_many :comments

  POSITIONS = ['developer', 'project manager', 'other']

  def to_s
    full_name.strip.empty? ? email : full_name
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def projects_member
    Project.in(id: memberships.map(&:project_id))
  end

  def issues_assigned
    Issue.in(assignee: self)
  end

  def technical?
    position == 'developer' || position == 'project manager'
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :deny_access, unless: :project_member?
  expose(:project)
  expose(:issue, attributes: :issue_params)
  expose(:issues) { project.issues }


  def create
    issue.creator = current_user
    if issue.save
      redirect_to project_issue_path(project, issue)
    else
      render :new
    end
  end

  def update
    if issue.save
      redirect_to project_issue_path(project, issue)
    else
      render :edit
    end
  end

  def assign_user
    issue = Issue.find(params[:id])
    issue.update(assignee: current_user) if current_user.technical?
    redirect_to project_issue_path(project, issue)
  end

  private
    def issue_params
      params.require(:issue).permit(:subject, :description, :priority, :type, :state)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  expose(:like)
  expose(:comment)

  def create
    unless comment.liked?(current_user) || comment.user == current_user
      like = comment.likes.build(user_id: current_user.id)
      like.save 
    end
    redirect_to :back
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :deny_access, unless: :project_member?
  expose(:topic)
  expose(:post, attributes: :post_params)
  expose(:posts)

  def create
    post.topic = topic
    post.user = current_user
    if post.save
      redirect_to project_topic_path(topic.project, topic)
    else
      redirect_to :back
    end
  end

  def update
    if post.save
      project_topic_path(topic.project, topic)
    else
      render :edit
    end
  end

  private
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  after_action :assign_member, only: [:create]
  expose(:user)
  expose(:project, attributes: :project_params)
  expose(:projects) { Project.all }

  def create
    project.user = current_user
    if project.save
      redirect_to project
    else
      render :new
    end
  end

  def update
    if project.save
      redirect_to project
    else
      render :edit
    end
  end

  def assign_member
    Membership.create(user_id: current_user.id, project_id: project.id)
  end

  protected
    def project_params
      params.require(:project).permit(:title, :description, :homepage)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  expose(:project)
  expose(:user)
  expose(:users)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper

  def show_assignee assignee
    assignee.present? ? assignee : 'unassigned'
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def show_homepage homepage
    if project.homepage.present?
      link_to homepage, "http://#{project.homepage}"
    else
      'unknown'
    end
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def show_time time
    time.strftime("%a %m/%d/%y")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/projects/_form.html.haml
.col-xs-6
  = simple_form_for project do |form|
    = form.input :title
    = form.input :description ,as: :text, input_html: { cols: 50, rows: 10 }
    = form.input :homepage

    = form.submit class: 'btn btn-primary'

app/views/projects/_overview.html.haml
.panel.panel-default
  .panel-heading Overview
  .panel-body
    %p
      %strong Homepage:
      = show_homepage(project.homepage)
    %p
      %strong Issues:
      %ul
        %li= "#{project.issues.open.count} open"
        %li= "#{project.issues.fixed.count} fixed"
        %li= "#{project.issues.count} total"
    %p
      %strong Members:
      = pluralize("#{project.members.count}", 'member')
      
      - if project.user == current_user
        =link_to 'Add member', new_project_membership_path(project), class: 'btn btn-default btn-xs'

app/views/projects/edit.html.haml
= render 'form'

app/views/projects/index.html.haml
.col-lg-12
  = link_to 'New Project', new_project_path, class: 'btn btn-primary pull-right'
  .bs-component
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th Title
          %th Members
          %th Created
      %tbody
        - projects.each do |project|
          %tr
            %td= link_to project.title, project
            %td= project.members.count
            %td= project.created_at.strftime("%B %d, %Y")

app/views/projects/new.html.haml
= render 'form'

app/views/projects/show.html.haml
%h3= project.title

.row
  .col-lg-12
    .bs-component
      %ul.nav.nav-tabs{style: "margin-bottom: 15px;"}
        %li.active
          %a{"data-toggle" => "tab", href: "#home"} Overview
        %li
          %a{"data-toggle" => "tab", href: "#issues"} Issues
        %li
          %a{"data-toggle" => "tab", href: "#members"} Members
        %li
          %a{"data-toggle" => "tab", href: "#discussions"} Discussions
  
      #myTabContent.tab-content

        #home.tab-pane.fade.active.in
          %p= render 'overview'

        #issues.tab-pane.fade
          .row
            .col-lg-12

              %button{type: "button", class: 'btn btn-default btn-sm', id: 'assigned-to-me'} Show assigned to me

              - if project.member?(current_user)
                = link_to 'Add issue', new_project_issue_path(project), class: 'btn btn-primary btn-sm'

              .bs-component
                %table.table.table-striped.table-hover
                  %thead
                    %tr
                      %th Subject
                      %th Priority
                      %th Type
                      %th State
                      %th Assignee
                  %tbody.hidden#mine
                    = render project.issues.mine(current_user)
                  %tbody#all
                    = render project.issues

        #members.tab-pane.fade
          .row
            .col-lg-12

              - if project.user == current_user
                = link_to 'Add member', new_project_membership_path(project), class: 'btn btn-default btn-sm'
              
              .bs-component
                %table.table.table-striped.table-hover
                  %thead
                    %tr
                      %th Name
                      %th Email
                      %th Position
                  %tbody
                    - project.members.each do |member|
                      %tr
                        %td= member.full_name
                        %td= member.email
                        %td= member.position
        

        #discussions.tab-pane.fade
          - if project.member?(current_user)
            = link_to 'Add topic', new_project_topic_path(project), class: 'btn btn-default btn-sm'

          %table.table.table-striped.table-hover
            %thead
              %tr
                %th Topic
                %th Posts
            %tbody
              = render project.topics